# -*- coding: utf-8 -*-
"""installation &imports

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lxdJaSNATbZS0n_M2CYx29PDkSmmqc8Z
"""

!pip install numpy

import numpy as np

